apiVersion: apps/v1
kind: Deployment
metadata:
  name: bucket-api
  namespace: tenant-abc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bucket-api
  template:
    metadata:
      labels:
        app: bucket-api
        tenant: tenant-abc
    spec:
      automountServiceAccountToken: false
      containers:
        - name: api
          image: europe-west1-docker.pkg.dev/kubernetes-object-store/demo-frontend/bucket-api:latest
          ports:
            - containerPort: 8000
          env:
            - name: BUCKET_NAME
              value: "tenant-abc-bucket-testdemo4234"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/var/run/gcp/creds.json"
          volumeMounts:
            - name: gcp-sa
              mountPath: /var/run/gcp
              readOnly: true
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
      volumes:
        - name: gcp-sa
          secret:
            secretName: tenant-abc-gcp-sa
            items:
              - key: attribute.private_key
                path: creds.json