apiVersion: storage.gcp.upbound.io/v1beta1
kind: Bucket
metadata:
  name: {{ .Values.bucketName }}
spec:
  deletionPolicy: Delete
  forProvider:
    location: {{ .Values.bucketLocation }}
    storageClass: STANDARD
    uniformBucketLevelAccess: true
    versioning:
      - enabled: false
  providerConfigRef:
    name: default