apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Values.tenantName }}-quota
  namespace: {{ .Values.tenantName }}
  labels:
    tenant: {{ .Values.tenantName }}
spec:
  hard:
    requests.cpu: {{ .Values.quota.requests.cpu | quote }}
    requests.memory: {{ .Values.quota.requests.memory | quote }}
    limits.cpu: {{ .Values.quota.limits.cpu | quote }}
    limits.memory: {{ .Values.quota.limits.memory | quote }}
    pods: {{ .Values.quota.pods | quote }}
    services: "10"
    persistentvolumeclaims: "0"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Values.tenantName }}-limitrange
  namespace: {{ .Values.tenantName }}
  labels:
    tenant: {{ .Values.tenantName }}
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: {{ .Values.resources.requests.cpu | quote }}
        memory: {{ .Values.resources.requests.memory | quote }}
      default:
        cpu: {{ .Values.resources.limits.cpu | quote }}
        memory: {{ .Values.resources.limits.memory | quote }}