apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.tenantName }}-app
  namespace: {{ .Values.tenantName }}
  labels:
    tenant: {{ .Values.tenantName }}
automountServiceAccountToken: false
imagePullSecrets:
  - name: {{ .Values.tenantName }}-gar-pull